"""add employee_meetings association table

Revision ID: ecf400c7f2d2
Revises: 2f792fb61891
Create Date: 2024-06-30 17:28:56.551977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf400c7f2d2'
down_revision = '2f792fb61891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_meetings',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('meetings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employees_meetings_employee_id_employees')),
    sa.ForeignKeyConstraint(['meetings_id'], ['meetings.id'], name=op.f('fk_employees_meetings_meetings_id_meetings')),
    sa.PrimaryKeyConstraint('employee_id', 'meetings_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_meetings')
    # ### end Alembic commands ###
